import express from 'express';
import axios from 'axios';
import jwt from 'jsonwebtoken';
import bcrypt from 'bcryptjs';
import crypto from 'crypto';
import User from '../models/User.js';
// Placeholder: Implement this function in your email service
import { sendEmail } from '../services/EmailService.js';


const router = express.Router();
const THINKIFIC_GRAPHQL_ENDPOINT = `https://api.thinkific.com/stable/graphql`;
const SALT_ROUNDS = 12;
const OTP_SERVICE_URL = process.env.OTP_SERVICE_URL || 'https://localhost:3015';

// Helper: Thinkific API fetch by email
async function fetchThinkificUser(email) {
    const response = await axios.post(
        THINKIFIC_GRAPHQL_ENDPOINT,
        {
            query: `query GetUserByEmail($email: EmailAddress!) {
        userByEmail(email: $email) {
          id
          email
          firstName
          lastName
          customProfileFields(first: 50) {
            edges { node { value label } }
          }
        }
      }`,
            variables: { email }
        },
        {
            headers: {
                Authorization: `Bearer ${process.env.THINKIFIC_API2_TOKEN}`,
                'X-Auth-Subdomain': process.env.THINKIFIC_SUBDOMAIN,
                'Content-Type': 'application/json'
            }
        }
    );

    if (response.data.errors) {
        console.log('Thinkific errors: ', response);
        throw new Error(response.data.errors.map(err => err.message).join(', '));
    }
    return response.data.data.userByEmail;
}

// Helper: Create local user from Thinkific data
async function createUserFromThinkific(thinkificUser) {
    // const generatedPassword = crypto.randomBytes(12).toString('hex');
    // const hashedPassword = await bcrypt.hash(generatedPassword, SALT_ROUNDS);

    const customFields = thinkificUser.customProfileFields.edges.reduce((acc, { node }) => {
        acc[node.label.toLowerCase()] = node.value;
        return acc;
    }, {});

    const roles = customFields.role?.split(',').map(r => r.trim()) || ['student'];

    const user = new User({
        email: thinkificUser.email,
        thinkificId: thinkificUser.id,
        firstName: thinkificUser.firstName,
        lastName: thinkificUser.lastName,
        // password: hashedPassword,
        roles,
        requiresPasswordReset: true
    });
    await user.save();

    // Send email with generated password
    // await sendEmail({
    //     to: thinkificUser.email,
    //     subject: 'Your Admin App Access',
    //     html: `<p>Hello ${thinkificUser.firstName},</p>
    //   <p>An account has been created for you in the Admin App.</p>
    //   <p>Your temporary password is: <strong>${generatedPassword}</strong></p>
    //   <p>Please log in and change your password as soon as possible.</p>
    //   <p>This password was generated by the Admin App.</p>`
    // });

    return user;
}

// Helper: Create JWT session and set cookie
function setSessionCookie(res, user) {
    const token = jwt.sign(
        { sub: user._id, roles: user.roles, reset: user.requiresPasswordReset },
        process.env.JWT_SECRET,
        { expiresIn: '1h', algorithm: 'HS512' }
    );
    res.cookie('session', token, {
        httpOnly: true,
        secure: process.env.NODE_ENV === 'production',
        sameSite: 'strict',
        maxAge: 3600000
    });
    return token;
}
// New OTP Service Helpers
async function generateOTP(email) {
    const response = await axios.post(`${OTP_SERVICE_URL}/api/otp/generate`, {
        email,
        type: "numeric",
        organization: "PCNC Academy",
        subject: "Your Verification Code"
    });
    return response.data;
}

async function verifyOTP(email, otp) {
    const response = await axios.post(`${OTP_SERVICE_URL}/api/otp/verify`, {
        email,
        otp
    });
    return response.status === 200  && response.data.message === 'OTP is verified';
}
// LOGIN ROUTE
router.post('/login', async (req, res) => {
    try {
        const { email, password, otp } = req.body;
        const emailNorm = email.trim().toLowerCase(); // Normalize email

        // Existing user with password
        const user = await User.findOne({ email: emailNorm });
        if (user?.password) {
            const validPassword = await bcrypt.compare(password, user.password);
            if (!validPassword) return res.status(401).json({ error: 'Invalid credentials' });

            setSessionCookie(res, user);
            return res.json({ success: true, user: formatUserResponse(user) });
        }

        // OTP Verification Flow
        if (otp) {
            const isValidOTP = await verifyOTP(emailNorm, otp.toString().trim());

            console.log("isValidOTP: ", isValidOTP)

            if (!isValidOTP) return res.status(401).json({ error: 'Invalid OTP' });

            if (!password || password.length < 8) {
                return res.status(400).json({ error: 'Password must be at least 8 characters' });
            }

            // Create/update user
            const thinkificUser = await fetchThinkificUser(emailNorm);
            if (!thinkificUser) return res.status(404).json({ error: 'User not found' });

            const hashedPassword = await bcrypt.hash(password, SALT_ROUNDS);
            let user = await User.findOneAndUpdate(
                { email: emailNorm },
                { password: hashedPassword, requiresPasswordReset: false },
                { new: true, upsert: true }
            );

            setSessionCookie(res, user);
            return res.json({ success: true, user: formatUserResponse(user) });
        }

        // Trigger OTP Generation
        await generateOTP(emailNorm);
        return res.status(202).json({
            success: true,
            message: 'OTP sent to email',
            requiresOTP: true
        });

    } catch (err) {
        console.error('Login error:', err);
        res.status(500).json({
            error: 'Login failed' + (process.env.NODE_ENV === 'development' ? ': ' + err.message : '')
        });
    }
});



// Helper to format user response
function formatUserResponse(user) {
    return {
        _id: user._id,
        id: user.thinkificId,
        email: user.email,
        firstName: user.firstName,
        lastName: user.lastName,
        roles: user.roles,
        requiresPasswordReset: user.requiresPasswordReset
    };
}

// PROFILE ROUTE
router.get('/profile', async (req, res) => {
    try {


        // Check if session exists
        if (!req.session || !req.session.user) {
            return res.status(401).json({ error: 'Unauthorized - No session found' });
        }

        // Get user from session data
        const user = await User.findById(req.session.user._id).select('-__v -password');
        if (!user) return res.status(404).json({ error: 'User not found' });

        res.json({
            id: user.thinkificId,
            email: user.email,
            firstName: user.firstName,
            lastName: user.lastName,
            roles: user.roles,
            lastLogin: user.lastLogin,
            requiresPasswordReset: user.requiresPasswordReset
        });
    } catch (err) {
        console.error('Profile Error:', err);
        res.status(500).json({ error: 'Failed to fetch profile' });
    }
});

// LOGOUT ROUTE
router.post('/logout', (req, res) => {
    req.session.destroy(err => {
        if (err) {
            console.error('Logout error:', err);
            return res.status(500).json({ error: 'Logout failed' });
        }
        res.clearCookie('connect.sid'); // Clear the session cookie
        res.json({ success: true });
    });
});



export default router;
