import express from 'express';
import axios from 'axios';
import jwt from 'jsonwebtoken';
import bcrypt from 'bcryptjs';
import crypto from 'crypto';
import User from '../models/User.js';
// Placeholder: Implement this function in your email service
import { sendEmail } from '../services/EmailService.js';
import ElvantoAuth from '../controllers/elvantoAuth.js';

const router = express.Router();
const THINKIFIC_GRAPHQL_ENDPOINT = `https://api.thinkific.com/stable/graphql`;
const SALT_ROUNDS = 12;

// Helper: Thinkific API fetch by email
async function fetchThinkificUser(email) {
    const response = await axios.post(
        THINKIFIC_GRAPHQL_ENDPOINT,
        {
            query: `query GetUserByEmail($email: EmailAddress!) {
        userByEmail(email: $email) {
          id
          email
          firstName
          lastName
          customProfileFields(first: 50) {
            edges { node { value label } }
          }
        }
      }`,
            variables: { email }
        },
        {
            headers: {
                Authorization: `Bearer ${process.env.THINKIFIC_API2_TOKEN}`,
                'X-Auth-Subdomain': process.env.THINKIFIC_SUBDOMAIN,
                'Content-Type': 'application/json'
            }
        }
    );

    if (response.data.errors) {
        console.log('Thinkific errors: ', response);
        throw new Error(response.data.errors.map(err => err.message).join(', '));
    }
    return response.data.data.userByEmail;
}

// Helper: Create local user from Thinkific data
async function createUserFromThinkific(thinkificUser) {
    const generatedPassword = crypto.randomBytes(12).toString('hex');
    const hashedPassword = await bcrypt.hash(generatedPassword, SALT_ROUNDS);

    const customFields = thinkificUser.customProfileFields.edges.reduce((acc, { node }) => {
        acc[node.label.toLowerCase()] = node.value;
        return acc;
    }, {});

    const roles = customFields.role?.split(',').map(r => r.trim()) || ['student'];

    const user = new User({
        email: thinkificUser.email,
        thinkificId: thinkificUser.id,
        firstName: thinkificUser.firstName,
        lastName: thinkificUser.lastName,
        password: hashedPassword,
        roles,
        requiresPasswordReset: true
    });
    await user.save();

    // Send email with generated password
    await sendEmail({
        to: thinkificUser.email,
        subject: 'Your Admin App Access',
        html: `<p>Hello ${thinkificUser.firstName},</p>
      <p>An account has been created for you in the Admin App.</p>
      <p>Your temporary password is: <strong>${generatedPassword}</strong></p>
      <p>Please log in and change your password as soon as possible.</p>
      <p>This password was generated by the Admin App.</p>`
    });

    return user;
}

// Helper: Create JWT session and set cookie
function setSessionCookie(res, user) {
    const token = jwt.sign(
        { sub: user._id, roles: user.roles, reset: user.requiresPasswordReset },
        process.env.JWT_SECRET,
        { expiresIn: '1h', algorithm: 'HS512' }
    );
    res.cookie('session', token, {
        httpOnly: true,
        secure: process.env.NODE_ENV === 'production',
        sameSite: 'strict',
        maxAge: 3600000
    });
    return token;
}

// LOGIN ROUTE
router.post('/login', async (req, res) => {
    try {
        const { email, password } = req.body;

        // 1. Try local user lookup
        let user = await User.findOne({ email });

        // 2. If not found, fetch from Thinkific and create locally
        if (!user) {
            const thinkificUser = await fetchThinkificUser(email);
            if (!thinkificUser) {
                return res.status(404).json({ error: 'User not found in Thinkific or locally.' });
            }
            user = await createUserFromThinkific(thinkificUser);
            return res.status(201).json({
                success: true,
                message: 'Account created. Check your email for your temporary password.',
                requiresPassword: true
            });
        }

        // 3. Validate password
        // const validPassword = await bcrypt.compare(password, user.password);
        // if (!validPassword) {
        //     return res.status(401).json({ error: 'Invalid credentials' });
        // }

        // 4. Set session cookie and return user info
        setSessionCookie(res, user);
        res.json({
            success: true,
            user: {
                id: user.thinkificId,
                email: user.email,
                firstName: user.firstName,
                lastName: user.lastName,
                roles: user.roles,
                requiresPasswordReset: user.requiresPasswordReset
            }
        });
    } catch (err) {
        console.error('Login error:', err);
        res.status(500).json({ error: 'Login failed. ' + (process.env.NODE_ENV === 'development' ? err.message : '') });
    }
});

// PROFILE ROUTE
router.get('/profile', async (req, res) => {
    try {
        const token = req.cookies.session;
        if (!token) return res.status(401).json({ error: 'Unauthorized' });

        const decoded = jwt.verify(token, process.env.JWT_SECRET);
        const user = await User.findById(decoded.sub).select('-__v -password');
        if (!user) return res.status(404).json({ error: 'User not found' });

        res.json({
            id: user.thinkificId,
            email: user.email,
            firstName: user.firstName,
            lastName: user.lastName,
            roles: user.roles,
            lastLogin: user.lastLogin,
            requiresPasswordReset: user.requiresPasswordReset
        });
    } catch (err) {
        console.error('Profile Error:', err);
        res.status(500).json({ error: 'Failed to fetch profile' });
    }
});

// LOGOUT ROUTE
router.post('/logout', (req, res) => {
    res.clearCookie('session');
    res.json({ success: true });
});

// Elvanto OAuth routes
router.get('/elvanto', ElvantoAuth.initiateAuth);
router.get('/elvanto/callback', ElvantoAuth.handleCallback);

export default router;
